export const actionTypes = {
    GET_PRODUCT_DATA:"GET_PRODUCT_DATA",
    UPDATE_QUANTITY:"UPDATE_QUANTITY",
    UDATE_LIVE_STATUS:"UPDATE_LIVE_STATUS",
    QUANT_UP:"QUANT_UP",
    QUANT_DOWN:"QUANT_DOWN"
}